# Generated by Django 4.2.16 on 2024-10-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurine',
            name='id_art',
        ),
    ]
